// TASK_ACTIONS

export const TASK_ACTION = {
  ADD: 'ADD_TASK',
  START: 'START_TASK',
  FINISH: 'FINISH_TASK',
  DELETE: 'DELETE_TASK',
  SET_FILTER: 'SET_FILTER',
  REQUEST: 'REQUEST_TASKS',
  RECEIVE: 'RECEIVE_TASKS',
};

// TASK_FILTER_ACTIONS
export const TASK_FILTER = {
  ALL: 'SHOW_ALL_TASKS',
  NOT_STARTED: 'SHOW_NOT_STARTED_TASKS',
  STARTED: 'SHOW_STARTED_TASKS',
  FINISHED: 'SHOW_FINISHED_TASKS',
};
